name: "Deploy on Comment"

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    name: Deploy
    # Only run if it#s a PR and the comment contains /deploy
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest

    steps:
      # Do the actual deployment (exit randomly with 0 or 1)
      - name: Deploy
        run: |
          echo "Deploying..."
          exit $(($RANDOM%2))
